<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-07T09:15:46 IST" name="Suite" finished-at="2023-06-07T09:16:03 IST" duration-ms="16736">
    <groups>
    </groups>
    <test started-at="2023-06-07T09:15:46 IST" name="Test" finished-at="2023-06-07T09:16:03 IST" duration-ms="16736">
      <class name="RahulShetty.ExtendReport.test3">
        <test-method signature="Initialdemo()[pri:0, instance:RahulShetty.ExtendReport.test3@2796aeae]" started-at="2023-06-07T09:15:46 IST" name="Initialdemo" finished-at="2023-06-07T09:16:03 IST" duration-ms="16664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialdemo -->
      </class> <!-- RahulShetty.ExtendReport.test3 -->
      <class name="RahulShetty.ExtendReport.test2">
        <test-method signature="Initialdemo()[pri:0, instance:RahulShetty.ExtendReport.test2@60129b9a]" started-at="2023-06-07T09:15:46 IST" name="Initialdemo" finished-at="2023-06-07T09:16:02 IST" duration-ms="15816" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at RahulShetty.ExtendReport.test2.Initialdemo(test2.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialdemo -->
      </class> <!-- RahulShetty.ExtendReport.test2 -->
      <class name="RahulShetty.ExtendReport.test1">
        <test-method signature="Initialdemo()[pri:0, instance:RahulShetty.ExtendReport.test1@78d6692f]" started-at="2023-06-07T09:15:46 IST" name="Initialdemo" finished-at="2023-06-07T09:16:03 IST" duration-ms="16568" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialdemo -->
      </class> <!-- RahulShetty.ExtendReport.test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
